name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: go version

    - name: Get dependencies
      run: |
        go mod tidy -compat=1.17
        
    - name: lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: v1.46.2
        # skip cache because of flaky behaviors
        skip-build-cache: true
        skip-pkg-cache: true
        
    - name: Run tests with coverage
      run: |
        go test -v ./... -coverprofile=coverage.txt
        bash <(curl -s https://codecov.io/bash) -f coverage.txt

    - name: Build
      run: go build -v .
