name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod tidy -compat=1.17
        
    - name: Run golangci linter
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
        golangci-lint run -v -c .golangci.yml
        
    - name: Run tests with coverage
      run: |
        go test -v ./... -coverprofile=coverage.txt
        bash <(curl -s https://codecov.io/bash) -f coverage.txt

    - name: Build
      run: go build -v .
